
# This is an example of how you can use Cromwell to interact with SLURM
# workload manager. *This is not a complete configuration file!* The
# content here should be copy pasted into the backend -> providers section
# of the cromwell.examples.conf in the root of the repository. You should
# uncomment lines that you want to define, and read carefully to customize
# the file. If you have any questions, please open an issue at
# https://www.github.com/broadinstitute/cromwell/issues

backend {
  default = slurm

  providers {
    slurm {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"                                                                                     
      config {
        runtime-attributes = """
        Int runtime_minutes = 600
        Int cpus = 1
        Int requested_memory_mb_per_core = 768
        String queue = "prod"
        String? docker
        """

        submit = """
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${out} \
              -e ${err} \
              -t ${runtime_minutes} \
              --partition ${queue} \
              ${"-c " + cpus} \
              --mem-per-cpu=${requested_memory_mb_per_core} \
              --wrap "/usr/bin/env bash ${script}"
        """

        submit-docker = """
            # Make sure the APPTAINER_CACHEDIR variable is set.
            TMPDIR=/scratch/tmp
            APPTAINER_TMPDIR=/scratch/tmp
            APPTAINER_CACHEDIR=/scratch/tmp

            APPTAINER_IMAGES=/bioinfo/apptainer_sif/

            APPTAINER_IMAGE_FILE=$(echo "${docker}" | sed 's#.*/##; s/:/_/g; s/$/.sif/;')
            if [ -f "$APPTAINER_IMAGES/$APPTAINER_IMAGE_FILE" ]; then
                echo "Using cached image file $APPTAINER_IMAGE_FILE"
                APPTAINER_CONTAINER_ARG="$APPTAINER_IMAGES/$APPTAINER_IMAGE_FILE"
            else
                >&2 echo "This image does not exist (private/locale repo) : $APPTAINER_IMAGES/$APPTAINER_IMAGE_FILE"
            fi
  
            # Submit the script to SLURM
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${cwd}/execution/stdout \
              -e ${cwd}/execution/stderr \
              -t ${runtime_minutes} \
              --partition ${queue} \
              ${"-c " + cpus} \
              --mem-per-cpu=${requested_memory_mb_per_core} \
              --wrap "apptainer exec --containall --bind ${cwd}:${docker_cwd} $APPTAINER_CONTAINER_ARG ${job_shell} ${docker_script}"
        """

        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"
      }
    }
  }
}
